### ISSUE TITLE
Pip requirements error

### ISSUE THREAD

**Issue by suraj-jayakumar** [pythonindia/junction#410]
Tried to install the requirements using new virtual environment of Anaconda [Windows 10]
When i run this
>pip install -r requirements-dev.txt

I get this error
>Collecting uwsgi==2.0.* (from -r requirements.txt (line 56))
  Using cached uwsgi-2.0.12.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\surajj~1\appdata\local\temp\pip-build-kidcbj\uwsgi\setup.py", line 3, in <module>
        import uwsgiconfig as uc
      File "uwsgiconfig.py", line 8, in <module>
        uwsgi_os = os.uname()[0]
    AttributeError: 'module' object has no attribute 'uname'

  >  ----------------------------------------
>Command "python setup.py egg_info" failed with error code 1 in >c:\users\surajj~1\appdata\local\temp\pip-build-kidcbj\uwsgi

**Comment by theskumar** [comment]
@suraj-jayakumar I am really sorry i don't have a window machine so I can't really help here.

That said, the uwsgi is not needed to be installed during development, so you should be able to comment  out that requirement from `requirements.txt` (do not commit that change) and then try installing the dependencies.
