### ISSUE TITLE
Create a management code to export reviewers vote

### ISSUE THREAD

**Issue by kracekumar** [pythonindia/junction#553]
The functionality is available here https://github.com/pythonindia/junction/blob/e8cefd7910f807873a9f0d7650f6868ccffbeac0/junction/proposals/dashboard.py#L287. You need to create a command line version.

**Comment by rahulxxarora** [comment]
Hey @kracekumar,  I would like to work on it. Can I?

**Comment by kracekumar** [comment]
@rahulxxarora Please go ahead.

**Comment by lladhibhutall** [comment]
@kracekumar  @palnabarun This seems fun, I can take a stab at it. A little guidance is appreciated.

**Comment by palnabarun** [comment]
So, this requires you to create a management command for Django, which would take in the conference slug as an argument, call the above-mentioned function and return you the reviewer votes for every proposal submitted for that conference. 

References
https://docs.djangoproject.com/en/1.8/howto/custom-management-commands/
https://docs.djangoproject.com/en/3.0/howto/custom-management-commands/

We are currently running on Django 1.9 so the Django documentation may be ab

**Comment by lladhibhutall** [comment]
@palnabarun I thought the issue had something to do with argparse or click, not very good with django if anybody else wanna take it, go-ahead.

**Comment by pradyunsg** [comment]
@lladhibhutall If you want to tackle a click+argparse issue, take a look at pip's issue related to its CLI: https://github.com/pypa/pip/issues/ 4659.

**Comment by aniruddha2000** [comment]
I would like to work on this issue

**Comment by aniruddha2000** [comment]
I wrote some code by reading the django documntation. But the test saying **python 2.7 tests are success** but **python 3.6 is failed**. @palnabarun can you review the code. Should I open a PR?

**Comment by palnabarun** [comment]
@aniruddha2000 -- #650 was raised to solve this. Maybe you should have a look there?

**Comment by aniruddha2000** [comment]
> @aniruddha2000 -- #650 was raised to solve this. Maybe you should have a look there?

yes but in #650 the code that the guy wrote that for create a csv file as well as storing the data right? But storing data functionality is already done in the below section right?
https://github.com/pythonindia/junction/blob/e8cefd7910f807873a9f0d7650f6868ccffbeac0/junction/proposals/dashboard.py#L287
So I have to create a command that create a csv file and then it the above function will write into the csv file right?

**Comment by aniruddha2000** [comment]
@palnabarun so I called the function and run the django command and it is giving me error below

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/aniruddha/Desktop/junction/.nox/dev/lib/python3.6/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/home/aniruddha/Desktop/junction/.nox/dev/lib/python3.6/site-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/aniruddha/Desktop/junction/.nox/dev/lib/python3.6/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/aniruddha/Desktop/junction/.nox/dev/lib/python3.6/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
TypeError: handle() missing 1 required positional argument: 'request'
```

**Comment by palnabarun** [comment]
**To anyone reading this after the https://github.com/pythonindia/junction/issues/553#issuecomment-602000342**

> So, this requires you to create a management command for Django, which would take in the conference slug as an argument, call the above-mentioned function and return you the reviewer votes for every proposal submitted for that conference.

This `call the above-mentioned function` is not correct. A function has to be written which has a similar behavior and not use the above-mentioned function.
